# Generated by Django 2.2 on 2019-06-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
